kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx2
  labels:
    name: nginx-deployment
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: nginx2
     role: nginx2
  template:
    spec:
      containers:
        - name: nginx2
          image: nginx:1.17.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.1
              memory: 128Mi
            requests:
              memory: 64Mi
              cpu: 0.05
    metadata:
      labels:
        name: nginx2
        role: nginx2
